# Generated by Django 4.1.6 on 2023-02-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_text',
            field=models.TextField(max_length=1000),
        ),
    ]
