# Generated by Django 4.1.6 on 2023-02-17 23:01

from django.db import migrations
from django.utils import timezone

def populate_db(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    Comment = apps.get_model('blog', 'Comment')
    blog_text = """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Consequat nisl vel pretium lectus. Purus semper eget duis at tellus at urna condimentum mattis. Varius sit amet mattis vulputate enim nulla aliquet. Dignissim cras tincidunt lobortis feugiat vivamus. Egestas dui id ornare arcu. Proin sed libero enim sed. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Est pellentesque elit ullamcorper dignissim cras. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Cras pulvinar mattis nunc sed blandit. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Suspendisse sed nisi lacus sed viverra tellus in. Egestas congue quisque egestas diam in arcu. Cursus risus at ultrices mi tempus imperdiet nulla.
    Donec massa sapien faucibus et. Molestie ac feugiat sed lectus. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Ut enim blandit volutpat maecenas volutpat. Facilisi etiam dignissim diam quis enim lobortis scelerisque fermentum dui. Congue eu consequat ac felis donec et odio pellentesque. Aliquet eget sit amet tellus. Enim eu turpis egestas pretium. Pellentesque nec nam aliquam sem et tortor. Porta non pulvinar neque laoreet suspendisse interdum.
    Fames ac turpis egestas maecenas pharetra. Erat velit scelerisque in dictum non consectetur. Et malesuada fames ac turpis egestas sed tempus. Diam sollicitudin tempor id eu nisl nunc mi ipsum. Fermentum iaculis eu non diam phasellus vestibulum lorem sed. Cras pulvinar mattis nunc sed blandit libero volutpat sed cras. Aliquet lectus proin nibh nisl condimentum. Quis vel eros donec ac odio tempor orci dapibus ultrices. Convallis a cras semper auctor. Dui faucibus in ornare quam. Aenean vel elit scelerisque mauris pellentesque. Nulla at volutpat diam ut venenatis tellus in metus vulputate.
    """
    comment_text= """
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet mattis vulputate enim nulla aliquet porttitor lacus. Consequat nisl vel pretium lectus. Purus semper eget duis at tellus at urna condimentum mattis. Varius sit amet mattis vulputate enim nulla aliquet. Dignissim cras tincidunt lobortis feugiat vivamus. Egestas dui id ornare arcu. Proin sed libero enim sed. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Est pellentesque elit ullamcorper dignissim cras. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Cras pulvinar mattis nunc sed blandit. Ligula ullamcorper malesuada proin libero nunc consequat interdum. Dolor purus non enim praesent elementum facilisis leo vel fringilla. Suspendisse sed nisi lacus sed viverra tellus in. Egestas congue quisque egestas diam in arcu. Cursus risus at ultrices mi tempus imperdiet nulla.
    """
    for i in range(8):
        blog = Blog(title_text="blog"+str(i), author_text="bot"+str(i), content_text=blog_text, posted_date=timezone.now())
        blog.save()
        for j in range(5):
            comment = Comment(blog_id=blog, commenter_text="bot"+str(j), email_text="bot"+str(j)+"@email.com", content_text=comment_text, posted_date=timezone.now())
            comment.save()

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_alter_blog_content_text_alter_comment_content_text'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]

