# Generated by Django 4.1.6 on 2023-03-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.FloatField()),
                ('from_unit', models.CharField(max_length=10)),
                ('from_unit_name', models.CharField(max_length=30)),
                ('to_value', models.FloatField()),
                ('to_unit', models.CharField(max_length=10)),
                ('to_unit_name', models.CharField(max_length=30)),
            ],
        ),
    ]
