# Generated by Django 4.1.6 on 2023-03-21 22:04

from django.db import migrations

# U.S. Ton: T
# Gram: g
# Troy Ounce: t_oz
# Kilogram: kg
# Imperial Pound: lb
# Ounce: oz

def populate_db(apps, schema_editor):

    Units = apps.get_model('unitconv', 'Units')

    T_g = Units()
    T_g.from_unit = 'T'
    T_g.from_unit_name = "Tons"
    T_g.from_value = 1
    T_g.to_unit = 'g'
    T_g.to_unit_name = "Grams"
    T_g.to_value = 907185
    T_g.save()

    T_t_oz = Units()
    T_t_oz.from_unit = 'T'
    T_t_oz.from_unit_name = "Tons"
    T_t_oz.from_value = 1
    T_t_oz.to_unit = 't_oz'
    T_t_oz.to_unit_name = "Troy Ounces"
    T_t_oz.to_value = 32666.7
    T_t_oz.save()

    T_kg = Units()
    T_kg.from_unit = 'T'
    T_kg.from_unit_name = "Tons"
    T_kg.from_value = 1
    T_kg.to_unit = 'kg'
    T_kg.to_unit_name = "Kilograms"
    T_kg.to_value = 1016.05
    T_kg.save()

    T_lb = Units()
    T_lb.from_unit = 'T'
    T_lb.from_unit_name = "Tons"
    T_lb.from_value = 1
    T_lb.to_unit = 'lb'
    T_lb.to_unit_name = "Pounds"
    T_lb.to_value = 2240
    T_lb.save()

    T_oz = Units()
    T_oz.from_unit = 'T'
    T_oz.from_unit_name = "Tons"
    T_oz.from_value = 1
    T_oz.to_unit = 'oz'
    T_oz.to_unit_name = "Ounces"
    T_oz.to_value = 35840
    T_oz.save()

    g_T = Units()
    g_T.from_unit = 'g'
    g_T.from_unit_name = "Grams"
    g_T.from_value = 1
    g_T.to_unit = 'T'
    g_T.to_unit_name = "Tons"
    g_T.to_value = 98421000
    g_T.save()

    g_t_oz = Units()
    g_t_oz.from_unit = 'g'
    g_t_oz.from_unit_name = "Grams"
    g_t_oz.from_value = 1
    g_t_oz.to_unit = 't_oz'
    g_t_oz.to_unit_name = "Troy Ounces"
    g_t_oz.to_value = 0.0321507
    g_t_oz.save()

    g_kg = Units()
    g_kg.from_unit = 'g'
    g_kg.from_unit_name = "Grams"
    g_kg.from_value = 1
    g_kg.to_unit = 'kg'
    g_kg.to_unit_name = "Kilograms"
    g_kg.to_value = 0.001
    g_kg.save()

    g_lb = Units()
    g_lb.from_unit = 'g'
    g_lb.from_unit_name = "Grams"
    g_lb.from_value = 1
    g_lb.to_unit = 'lb'
    g_lb.to_unit_name = "Pounds"
    g_lb.to_value = 0.00220462
    g_lb.save()

    g_oz = Units()
    g_oz.from_unit = 'g'
    g_oz.from_unit_name = "Grams"
    g_oz.from_value = 1
    g_oz.to_unit = 'oz'
    g_oz.to_unit_name = "Ounces"
    g_oz.to_value = 0.035274
    g_oz.save()

    t_oz_T = Units()
    t_oz_T.from_unit = 't_oz'
    t_oz_T.from_unit_name = "Troy Ounces"
    t_oz_T.from_value = 1
    t_oz_T.to_unit = 'T'
    t_oz_T.to_unit_name = "Tons"
    t_oz_T.to_value = 0.000030612
    t_oz_T.save()

    t_oz_g = Units()
    t_oz_g.from_unit = 't_oz'
    t_oz_g.from_unit_name = "Troy Ounces"
    t_oz_g.from_value = 1
    t_oz_g.to_unit = 'g'
    t_oz_g.to_unit_name = "Grams"
    t_oz_g.to_value = 31.1035
    t_oz_g.save()

    t_oz_kg = Units()
    t_oz_kg.from_unit = 't_oz'
    t_oz_kg.from_unit_name = "Troy Ounces"
    t_oz_kg.from_value = 1
    t_oz_kg.to_unit = 'kg'
    t_oz_kg.to_unit_name = "Kilograms"
    t_oz_kg.to_value = 0.0311035
    t_oz_kg.save()

    t_oz_lb = Units()
    t_oz_lb.from_unit = 't_oz'
    t_oz_lb.from_unit_name = "Troy Ounces"
    t_oz_lb.from_value = 1
    t_oz_lb.to_unit = 'lb'
    t_oz_lb.to_unit_name = "Pounds"
    t_oz_lb.to_value = 0.0685714
    t_oz_lb.save()

    t_oz_oz = Units()
    t_oz_oz.from_unit = 't_oz'
    t_oz_oz.from_unit_name = "Troy Ounces"
    t_oz_oz.from_value = 1
    t_oz_oz.to_unit = 'oz'
    t_oz_oz.to_unit_name = "Ounces"
    t_oz_oz.to_value = 1.09714
    t_oz_oz.save()

    kg_T = Units()
    kg_T.from_unit = 'kg'
    kg_T.from_unit_name = "Kilograms"
    kg_T.from_value = 1
    kg_T.to_unit = 'T'
    kg_T.to_unit_name = "Tons"
    kg_T.to_value = 0.000984207
    kg_T.save()

    kg_g = Units()
    kg_g.from_unit = 'kg'
    kg_g.from_unit_name = "Kilograms"
    kg_g.from_value = 1
    kg_g.to_unit = 'g'
    kg_g.to_unit_name = "Grams"
    kg_g.to_value = 1000
    kg_g.save()

    kg_t_oz = Units()
    kg_t_oz.from_unit = 'kg'
    kg_t_oz.from_unit_name = "Kilograms"
    kg_t_oz.from_value = 1
    kg_t_oz.to_unit = 't_oz'
    kg_t_oz.to_unit_name = "Troy Ounces"
    kg_t_oz.to_value = 32.1507
    kg_t_oz.save()

    kg_lb = Units()
    kg_lb.from_unit = 'kg'
    kg_lb.from_unit_name = "Kilograms"
    kg_lb.from_value = 1
    kg_lb.to_unit = 'lb'
    kg_lb.to_unit_name = "Pounds"
    kg_lb.to_value = 2.20462
    kg_lb.save()

    kg_oz = Units()
    kg_oz.from_unit = 'kg'
    kg_oz.from_unit_name = "Kilograms"
    kg_oz.from_value = 1
    kg_oz.to_unit = 'oz'
    kg_oz.to_unit_name = "Ounces"
    kg_oz.to_value = 35.274
    kg_oz.save()

    oz_T = Units()
    oz_T.from_unit = 'oz'
    oz_T.from_unit_name = "Ounces"
    oz_T.from_value = 1
    oz_T.to_unit = 'T'
    oz_T.to_unit_name = "Tons"
    oz_T.to_value = 0.000027902
    oz_T.save()

    oz_g = Units()
    oz_g.from_unit = 'oz'
    oz_g.from_unit_name = "Ounces"
    oz_g.from_value = 1
    oz_g.to_unit = 'g'
    oz_g.to_unit_name = "Grams"
    oz_g.to_value = 28.3495
    oz_g.save()

    oz_t_oz = Units()
    oz_t_oz.from_unit = 'oz'
    oz_t_oz.from_unit_name = "Ounces"
    oz_t_oz.from_value = 1
    oz_t_oz.to_unit = 't_oz'
    oz_t_oz.to_unit_name = "Troy Ounces"
    oz_t_oz.to_value = 0.911458
    oz_t_oz.save()

    oz_kg = Units()
    oz_kg.from_unit = 'oz'
    oz_kg.from_unit_name = "Ounces"
    oz_kg.from_value = 1
    oz_kg.to_unit = 'kg'
    oz_kg.to_unit_name = "Kilograms"
    oz_kg.to_value = 0.0283495
    oz_kg.save()

    oz_lb = Units()
    oz_lb.from_unit = 'oz'
    oz_lb.from_unit_name = "Ounces"
    oz_lb.from_value = 1
    oz_lb.to_unit = 'lb'
    oz_lb.to_unit_name = "Pounds"
    oz_lb.to_value = 0.0625
    oz_lb.save()

    lb_T = Units()
    lb_T.from_unit = 'lb'
    lb_T.from_unit_name = "Pounds"
    lb_T.from_value = 1
    lb_T.to_unit = 'T'
    lb_T.to_unit_name = "Tons"
    lb_T.to_value = 0.000446429
    lb_T.save()

    lb_g = Units()
    lb_g.from_unit = 'lb'
    lb_g.from_unit_name = "Pounds"
    lb_g.from_value = 1
    lb_g.to_unit = 'g'
    lb_g.to_unit_name = "Grams"
    lb_g.to_value = 453.592
    lb_g.save()

    lb_t_oz = Units()
    lb_t_oz.from_unit = 'lb'
    lb_t_oz.from_unit_name = "Pounds"
    lb_t_oz.from_value = 1
    lb_t_oz.to_unit = 't_oz'
    lb_t_oz.to_unit_name = "Troy Ounces"
    lb_t_oz.to_value = 14.5833
    lb_t_oz.save()

    lb_kg = Units()
    lb_kg.from_unit = 'lb'
    lb_kg.from_unit_name = "Pounds"
    lb_kg.from_value = 1
    lb_kg.to_unit = 'kg'
    lb_kg.to_unit_name = "Kilograms"
    lb_kg.to_value = 0.453592
    lb_kg.save()

    lb_oz = Units()
    lb_oz.from_unit = 'lb'
    lb_oz.from_unit_name = "Pounds"
    lb_oz.from_value = 1
    lb_oz.to_unit = 'oz'
    lb_oz.to_unit_name = "Ounces"
    lb_oz.to_value = 16
    lb_oz.save()

class Migration(migrations.Migration):

    dependencies = [
        ('unitconv', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
