# Generated by Django 4.1.6 on 2023-03-15 21:48

from django.db import migrations

def populate_db(apps, schema_editor):
    Operator = apps.get_model('calculator', 'Operator')

    plusOperator = Operator(name="plus", symbol="+")
    plusOperator.save()
    minusOperator = Operator(name="minus", symbol="-")
    minusOperator.save()
    multiplyOperator = Operator(name="multiply", symbol="*")
    multiplyOperator.save()
    divideOperator = Operator(name="divide", symbol="/")
    divideOperator.save()
    modulusOperator = Operator(name="modulus", symbol="%")
    modulusOperator.save()
    exponentOperator = Operator(name="exponent", symbol="**")
    exponentOperator.save()

class Migration(migrations.Migration):
    dependencies = [
        ('calculator', '0002_rename_result_expression_jsanswer_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
