# Generated by Django 4.1.6 on 2023-02-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('author_text', models.CharField(max_length=100)),
                ('content_text', models.TextField(max_length=500)),
                ('posted_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_text', models.CharField(max_length=200)),
                ('email_text', models.EmailField(max_length=100)),
                ('content_text', models.TextField(max_length=500)),
                ('posted_date', models.DateTimeField(verbose_name='date published')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
            ],
        ),
    ]
